### ISSUE TITLE
Required Click version is not found.

### ISSUE THREAD

**Issue by nazrulworld** [plone/plonecli#11]
* Plone CLI version:  0.1.0a4
* Python version: 2.7.12
* Operating System: Ubuntu 16.04

### Description

Searching for Click>=6.8a99 Reading https://pypi.python.org/simple/Click/ No local packages or working download links found for Click>=6.8a99 error: Could not find suitable distribution for Requirement.parse('Click>=6.8a99')
### What I Did

```
pip install plonecli
```

**Comment by jaroel** [comment]
Please see the note at https://github.com/plone/plonecli#installation

**Comment by kakshay21** [comment]
@jaroel Facing the same error even while running
```
pip install -r https://raw.githubusercontent.com/plone/plonecli/master/requirements.txt
```
Changing  ```Click>=6.8a99``` to  ```Click```
seems to work. It downloads the latest version of Click 
```click==7.0.dev0```

**Comment by MrTango** [comment]
As @jaroel already mentioned, you have to use easy_install instead of pip, until the next version of Click is released. Unfortunately the maintainers are recently not very responsive.
We still waiting for the release.
