### ISSUE TITLE
Make use of an egg cache to speed up install times

### ISSUE THREAD

**Issue by pigeonflight** [plone/plonecli#14]
The Plone unified installer provides a cache of some of the packages needed when running buildout. 
This reduces the installation time.
The Plone heroku buildpack has a good example of "borrowing" the build cache of the unified installer to speed up installation see:
https://github.com/plone/heroku-buildpack-plone/blob/9c115ebd9c0471ebab679f17a294880eb2f86b4d/bin/compile

A similar approach could be taken by plonecli.
## Proposed implementation

A cli command called ``install_package_cache``.
When invoked it would:
1. download the unified installer to a temporary directory
2. unpack the installer into the temporary directory
3. unpack the cache into the target egg directory
4. clean up by removing the temporary directory

The ``ploncli build`` command would invoke ``install_package_cache`` as part of the build process.

**Comment by MrTango** [comment]
I use a global egg cache, otherwise you have to download every and fill the cache for every project.
