### ISSUE TITLE
Add version option

### ISSUE THREAD

**Issue by MrTango** [plone/plonecli#21]
It would be nice to add a version option, which shows the installed version of plonecli and maybe even bobtemplate.plone too.

```
$ plonecli -v
plonecli: 0.1.1
bobtemplates.plone: 3.0.0
```

**Comment by ArhantJain** [comment]
On the first hand, I'm trying to show only plonecli  version using " **plonecli -v** " command.But I'm unable to find the file where all the rules about commands are written.

Please help me, from where should I start? Also, in present scenario how should we find the installed version of plonecli?
This is the listed files and folders in the directory ( where plonecli is installed) 
![plonecli](https://user-images.githubusercontent.com/23739699/38280729-90c0ab18-37c4-11e8-9af5-6f4007c81377.png)

**Comment by kakshay21** [comment]
@ArhantJain this is with GSoC label, GSoC student should do that. But feel free to try if you want to.
Earlier `-v` was used to show verbose. Now we want to use `-v` to show version details of plonecli.
You should start by understanding [cli.py](https://github.com/plone/plonecli/blob/master/plonecli/cli.py).

**Comment by ArhantJain** [comment]
Dear @kakshay21,
I have applied for GSoC2018 under the Project: Command Line Plone Tools which has the same stuff as mentioned in the issue.
So, Yaa I'm a GSoC Student. :) 

Thanks for the help, I will follow the link.

**Comment by kakshay21** [comment]
@ArhantJain If you regularly monitor this repo then you would know this issue was created very recently. And @MrTango attached the label after the proposal deadline, which could possibly mean that this issue was created for "Selected GSoC Student". But this is open source and you can work on it by all means.
BTW, I've also applied for the same project. Let's hope for the best.

**Comment by MrTango** [comment]
We will go for --versions, as we don't want it to show up in autocomplete
