### ISSUE TITLE
Add a "--version" and "-v" commands to show plonecli installed version.

### ISSUE THREAD

**Issue by idgserpro** [plone/plonecli#27]
* Plone CLI version:

0.2.0

* Python version:

2.7.9

* Operating System:

Ubuntu 16.04

**Comment by kakshay21** [comment]
@idgserpro  `-v` is generally used for verbose
for this reason, we've used `-V`, `--version`

**Comment by kakshay21** [comment]
closing now
see https://github.com/plone/plonecli/pull/30
