### ISSUE TITLE
Changes doesn't show any effect

### ISSUE THREAD

**Issue by mzfr** [plone/plonecli#40]
* Plone CLI version: 0.3.1.dev0
* Python version: 3.7
* Operating System: Manjaro

### Description

I am trying to make changes to the plonecli so I set up a development environment but it doesn't show any changes. I tried adding and removing lines of code but there wasn't any change on the working.

### What I Did

I tried to remove all the code from the `cli.py` and then ran `plonecli -h` but I still get the menu which shouldn't be the case because there wasn't any code in `cli.py`.

**Comment by kakshay21** [comment]
@mzfr did you installed the changed version?
try running `python setup.py install`

**Comment by kakshay21** [comment]
@mzfr Just a friendly suggestion, try reading the code and get a rough idea of how each components are working and then start solving issues.

**Comment by kakshay21** [comment]
@mzfr I don't think it's an issue. Most probably, your environment is picking the wrong version of plonecli. 
Try to create a clean environment and install it from master instead of pip way.
Let me know if this works

**Comment by mzfr** [comment]
@kakshay21 Well I decide to directly invoke the file i.e ran `python plonecli/cli.py -h`
