### ISSUE TITLE
support build for a given path

### ISSUE THREAD

**Issue by mzfr** [plone/plonecli#43]
Currently When we try to run `plonecli build` it only works for the current directory but it doesn't work for any specific directory like `plonecli build collective.todo`, it actually takes collective.todo as a command.
It would be better if we support building with a given path.

Also, this issue will decrease our work that is to be done in issue #25 (Add init command).

**Comment by MrTango** [comment]
Can you explain what benefit this brings, i don't see the point in building a package from somewhere outside the package.
Plonecli allows you already to build the package from anywhere inside the package structure, so one don't need to be in the root folder to do so. #25 is not benefiting either from this.
What we need there is to update an existing package to be compatible with plonecli/bobtemplates.plone.

**Comment by mzfr** [comment]
Hey @MrTango, I opened this issue a very long time ago and don't remember my thinking behind it. 

So I'll just go ahead and close the issue :)
