### ISSUE TITLE
plonecli adds python2.7 trove classifier when I enter plone 5.2 and python3.7

### ISSUE THREAD

**Issue by fredvd** [plone/plonecli#56]
Found during the testing training @ ploneconf 2019 by Paul:

* Plone CLI version: 1.1
* Python version:  3.7
* Operating System: OS X 10.14

when you create an add'on for plone 5.2 and getting asked the python version you pass in python3.7:

```
--> Do you want me to initialze a GIT repository in your new package? (y/n) [y]: y

--> Plone version [5.1]: 5.2

--> Python version for virtualenv [python2.7]: python3.7
```

 the setup.py still contains the trove classifiers:

```
  classifiers=[
        "Environment :: Web Environment",
        "Framework :: Plone",
        "Framework :: Plone :: Addon",
        "Framework :: Plone :: 5.2",
        "Programming Language :: Python",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Operating System :: OS Independent",
        "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    ],
```

**Comment by idgserpro** [comment]
I think this should be added to https://github.com/plone/bobtemplates.plone. We've added more inconsistencies of this nature there:

https://github.com/plone/bobtemplates.plone/issues/383
https://github.com/plone/bobtemplates.plone/issues/391

**Comment by MrTango** [comment]
This is intended, just because you choose a default Version, doesn't mean you don't want to support older Python and Plone versions with your addon. It's easy to remove them if you don't want to support older versions.
