### ISSUE TITLE
Migrating plonecli to cookiecutter

### ISSUE THREAD

**Issue by pigeonflight** [plone/plonecli#62]
It would be interesting to migrate plonecli to cookiecutter. 
Cookiecutter is more widely used system and is already used in the Plone community (e.g. https://github.com/kitconcept/cookiecutter-plone )
And you get to justify this:
![image](https://user-images.githubusercontent.com/31827/97801757-f4f7d500-1c0c-11eb-9694-1ffc1e11f73b.png)

**Comment by MrTango** [comment]
haha, nice logo, but no thx.
We will stay with mr.bob, as most of the work is done in bobtemplates.plone and when i compared both tools back then, coockiecutter was offering me nothing more than mr.bob. The real benefit with the sub-commands comes from bobtemplates.plone it self.

**Comment by pigeonflight** [comment]
Understood, I suspected the mr.bob dependency was an important consideration 👍
