### ISSUE TITLE
Default output

### ISSUE THREAD

**Issue by jensens** [plone/plonecli#8]
1. Just entering ``plonecli`` should output at least something, best something meaningful, like basic help.
2. I expect ``plonecli -h`` to write out the same as ``plonecli --help``.

**Comment by mrsaicharan1** [comment]
I'd like to work on this by printing out additional commands which may be helpful to the end user. We could also include information on how to create add-ons and modify them through the cli.

**Comment by mrsaicharan1** [comment]
Can you point me to the shell script which handles these commands? I was unable to find it.

**Comment by kakshay21** [comment]
I guess [here](https://github.com/plone/plonecli/blob/master/plonecli/cli.py) 
@mrsaicharan1
