### ISSUE TITLE
Add "--config" option to plonecli "create" and "add" commands

### ISSUE THREAD

**Issue by me-kell** [plone/plonecli#80]
It would be very helpful if `plonecli` could accept a configuration file to specify mr.bob variables.

This could be easily be done in the functions `create` and `add` in `plonecli.cli.py` by adding a `click.option` and extending the list passed to `mrbobmain` as follows:

https://github.com/plone/plonecli/blob/d49d7c79613ac3324e85da45c5a8daeb09cd0a1f/plonecli/cli.py#L77

```python
...
@click.option("-c", "--config", default=None, help="Configuration file to specify either [mr.bob] or [variables] sections.")
...
def create(context, template, name, config):
    ...
    mrbob_args = [bobtemplate, "-O", name]
    if config is not None:
        mrbob_args.extend(["-c", config])
    mrbobmain(mrbob_args)

```

https://github.com/plone/plonecli/blob/d49d7c79613ac3324e85da45c5a8daeb09cd0a1f/plonecli/cli.py#L97

```python
@click.option("-c", "--config", default=None, help="Configuration file to specify either [mr.bob] or [variables] sections.")
...
def add(context, template, config):
    ...
    mrbob_args = [bobtemplate]
    if config is not None:
        mrbob_args.extend(["-c", config])
    mrbobmain(mrbob_args)
```

**Comment by MrTango** [comment]
You can set these variables in your home in:

```
$ cat ~/.mrbob 
[mr.bob]
verbose = False

[variables]
# all variables answered here, will not being ask again:

author.name = Maik Derstappen
author.email = md@derico.de
author.github.user = MrTango
package.venv.disabled = n
package.git.disabled = n
package.git.init = y
package.git.autocommit = y

[defaults]
# set your default values for questions here, they questions are still being ask
# but with your defaults:

plone.version = 5.2.5
#dexterity_type_global_allow = n
#dexterity_type_filter_content_types = y
#dexterity_type_activate_default_behaviors = n
#dexterity_type_supermodel = y
python.version = /home/maik/.pyenv/versions/3.8.11/bin/python3.8

```

the existing config command is generating this config for you after asking some questions.

What would the purpose of additional configuration be?

**Comment by me-kell** [comment]
@MrTango "What would the purpose of additional configuration be?"
The purpose would be to pass the a config file to `mrbob --config`.

IMHO there is no need to obfuscate mrbob's config option.

When creating several different templates with `mrbob` setting the variables in `~/.mrbob` is not optimal.
Using specific config files is reusable, reproducible and allows adding those config files to a version control system.

**Comment by erral** [comment]
We also need this to be able to call plonecli through cookiecutter-plone-starter see https://github.com/collective/cookiecutter-plone-starter/pull/25
