### ISSUE TITLE
Syntax Error after creating the package

### ISSUE THREAD

**Issue by jensens** [plone/plonecli#9]
Using Python 3.6 accepting the defaults while ``plonecli create addon`` the generated package is syntactical wrong:

```
Develop: '/home/workspacejensens/pro/collective.es.index/.'
Traceback (most recent call last):
  File "/tmp/tmpJQE6LY", line 14, in <module>
    exec(compile(f.read(), '/home/workspacejensens/pro/collective.es.index/./setup.py', 'exec'))
  File "/home/workspacejensens/pro/collective.es.index/./setup.py", line 31
    author='b'Jens W. Klein'',
                 ^
SyntaxError: invalid syntax
```

**Comment by mrsaicharan1** [comment]
I'd like to try fixing this. Can you tell me when this occurs exactly?

**Comment by jensens** [comment]
Best if you install python 3.6 and use plonecli from source as described above, then fill in some author name and you will run into the problem.

**Comment by mrsaicharan1** [comment]
I've installed python3.6, and I've created a dummy add-on to test it. I've entered an author name..I didn't run into any such problem :/. I've been asked for the email, description etc.. after this. Maybe I've got you wrong somewhere?

**Comment by jensens** [comment]
Hmm, maybe it was fixed meanwhile? I can xcheck later.
